-- require("config.helpers").safeSetup("oc-2", {
-- 	overrides = {
-- 		NormalFloat = { bg = "none" },
-- 		FloatBorder = { bg = "none" },
-- 		FloatTitle = { bg = "none" },
-- 		OpencodeBorder = { bg = "none", fg = "none" },
-- 	},
-- })
--
-- vim.cmd([[colorscheme oc-2]])
